version: '3'

services:
  mysql:
    container_name: mysql
    image: mariadb:latest
    volumes:
      - ../db/data:/var/lib/mysql
    env_file: ../config/mysql.env
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - '8888:80'
    volumes:
      - ../wordpress:/var/www/html
    env_file: ../config/wordpress.env
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
