version: '3'

services:
    mysql:
        container_name: baht-mysql
        hostname: baht-mysql
        build: ./mysql
        volumes:
            - ../db/data:/var/lib/mysql
            - ../db/backup:/backup
        env_file: ../config/mysql.env
        restart: always

    wordpress:
        container_name: baht-app
        hostname: baht-app
        build: ./wordpress
        volumes:
            - ../wordpress:/var/www/html
        env_file:
            - ../config/wordpress.env
            - ../config/letsencrypt.env
        links:
            - mysql
        depends_on:
            - mysql
        ports:
            - "80:80"
            - "443:443"
        restart: always

    batch:
        container_name: baht-batch
        hostname: baht-batch
        build: ./batch
        volumes:
            - ../batch:/usr/local/batch
        env_file: ../config/db.env
        links:
            - mysql
        depends_on:
            - mysql
        command: bash /usr/local/batch/execute.sh
